#!/usr/bin/env bash
tmux_session=$1
tmux has-session -t $tmux_session

if [ $? != 0 ]
then
  if [ $tmux_session == 'work' ]
  then
    # Create a work session
    tmux new-session -s work -n editor -d

    # Open into the geckoboard app and fire up Vim
    tmux send-keys -t work 'cd ~/development/app' C-m
    tmux send-keys -t work 'vim' C-m
    # split off a console under the editor
    tmux split-window -v -p 22 -t work
    tmux send-keys -t work 'cd ~/development/app;clear' C-m
    # split again and tail logs
    tmux split-window -h -t work
    tmux send-keys -t work 'tail -f /var/log/applications/*.log' C-m
    tmux select-pane -t work:0.1

    # Select Vim ready to code
    tmux select-window -t work:0
    tmux select-pane -t work:0.0
  fi
fi

tmux attach -t $tmux_session
