#!/usr/bin/env bash

tmux_session=$1
tmux has-session -t $tmux_session

if [ $? != 0 ]
then
  if [ $tmux_session == 'work' ]
  then
    # Create a work session
    tmux new-session -s work -n editor -d

    tmux send-keys -t work 'cd ~' C-m
    tmux send-keys -t work 'vim' C-m

    # split off a console under the editor
    tmux split-window -v -p 22 -t work
    tmux send-keys -t work 'cd ~;clear' C-m

    # Select Vim ready to code
    tmux select-window -t work:0
    tmux select-pane -t work:0.0
  fi
fi

tmux attach -t $tmux_session
